import type { CatalogCategory, CatalogProduct, ProductSearchResult } from './types'

export const FALLBACK_CATEGORIES: CatalogCategory[] = [
  {
    id: 'electronics',
    name: 'Electronics',
    slug: 'electronics',
    children: [
      { id: 'audio', name: 'Audio', slug: 'audio', children: [] },
      { id: 'wearables', name: 'Wearables', slug: 'wearables', children: [] },
    ],
  },
  {
    id: 'fashion',
    name: 'Fashion',
    slug: 'fashion',
    children: [
      { id: 'shoes', name: 'Shoes', slug: 'shoes', children: [] },
      { id: 'apparel', name: 'Apparel', slug: 'apparel', children: [] },
    ],
  },
  {
    id: 'beauty',
    name: 'Beauty',
    slug: 'beauty',
    children: [{ id: 'skincare', name: 'Skincare', slug: 'skincare', children: [] }],
  },
  {
    id: 'home',
    name: 'Home',
    slug: 'home',
    children: [{ id: 'office', name: 'Office', slug: 'office', children: [] }],
  },
  {
    id: 'pets',
    name: 'Pets',
    slug: 'pets',
    children: [
      { id: 'dog', name: 'Dog', slug: 'dog', children: [] },
      { id: 'cat', name: 'Cat', slug: 'cat', children: [] },
    ],
  },
]

const products: CatalogProduct[] = [
  {
    id: 'PROD001',
    name: 'Nike Air Zoom Runner',
    slug: 'nike-air-zoom-runner',
    description: 'Lightweight running shoes with responsive cushioning.',
    price: 49.99,
    listPrice: 79.99,
    discountPercentage: 20,
    stockQuantity: 50,
    brand: { id: 1, name: 'Nike', slug: 'nike' },
    categories: [
      { id: 'shoes', name: 'Shoes', slug: 'shoes' },
      { id: 'fashion', name: 'Fashion', slug: 'fashion' },
    ],
    images: [
      'https://images.unsplash.com/photo-1542291026-7eec264c27ff?w=800',
    ],
    tags: ['best-seller', 'new-arrival'],
    attributes: { color: ['Black'], size: ['10'], material: ['Mesh'] },
    avgRating: 4.6,
    numReviews: 128,
    numSales: 540,
  },
  {
    id: 'PROD002',
    name: 'Adidas Ultraboost Everyday',
    slug: 'adidas-ultraboost-everyday',
    description: 'Everyday trainers built for comfort and style.',
    price: 89.99,
    listPrice: 120,
    discountPercentage: 15,
    stockQuantity: 40,
    brand: { id: 2, name: 'Adidas', slug: 'adidas' },
    categories: [{ id: 'shoes', name: 'Shoes', slug: 'shoes' }],
    images: [
      'https://images.unsplash.com/photo-1606107557195-0e29a4b5b4aa?w=800',
    ],
    tags: ['featured', 'best-seller'],
    attributes: { color: ['White'], size: ['9'], material: ['Knit'] },
    avgRating: 4.7,
    numReviews: 210,
    numSales: 390,
  },
  {
    id: 'PROD003',
    name: 'Sony WH-1000XM5 Headphones',
    slug: 'sony-wh-1000xm5',
    description: 'Industry-leading noise canceling wireless headphones.',
    price: 328,
    listPrice: 399.99,
    discountPercentage: 18,
    stockQuantity: 25,
    brand: { id: 3, name: 'Sony', slug: 'sony' },
    categories: [
      { id: 'audio', name: 'Audio', slug: 'audio' },
      { id: 'electronics', name: 'Electronics', slug: 'electronics' },
    ],
    images: [
      'https://images.unsplash.com/photo-1618366712010-f4ae9c647dcb?w=800',
    ],
    tags: ['todays-deal', 'best-seller'],
    attributes: { color: ['Black'], connectivity: ['Bluetooth'] },
    avgRating: 4.8,
    numReviews: 980,
    numSales: 1200,
  },
  {
    id: 'PROD004',
    name: 'Apple Watch SE GPS',
    slug: 'apple-watch-se-gps',
    description: 'Fitness tracking smartwatch with crash detection.',
    price: 249,
    listPrice: 279,
    discountPercentage: 10,
    stockQuantity: 30,
    brand: { id: 4, name: 'Apple', slug: 'apple' },
    categories: [{ id: 'wearables', name: 'Wearables', slug: 'wearables' }],
    images: [
      'https://images.unsplash.com/photo-1434493789847-2f02dc6ca35d?w=800',
    ],
    tags: ['featured', 'new-arrival'],
    attributes: { color: ['Starlight'], connectivity: ['GPS'] },
    avgRating: 4.5,
    numReviews: 640,
    numSales: 800,
  },
  {
    id: 'PROD005',
    name: 'CeraVe Hydrating Cleanser',
    slug: 'cerave-hydrating-cleanser',
    description: 'Gentle face wash with ceramides for normal to dry skin.',
    price: 14.99,
    listPrice: 18.99,
    discountPercentage: 21,
    stockQuantity: 100,
    brand: { id: 5, name: 'CeraVe', slug: 'cerave' },
    categories: [{ id: 'skincare', name: 'Skincare', slug: 'skincare' }],
    images: [
      'https://images.unsplash.com/photo-1556228578-0d85b1a4d571?w=800',
    ],
    tags: ['best-seller', 'todays-deal'],
    attributes: { 'skin-type': ['Dry'], size: ['16 oz'] },
    avgRating: 4.7,
    numReviews: 4500,
    numSales: 2200,
  },
  {
    id: 'PROD006',
    name: 'Purina Pro Plan Dog Food 18lb',
    slug: 'purina-pro-plan-dog-18lb',
    description: 'High-protein kibble for active adult dogs.',
    price: 42.99,
    listPrice: 49.99,
    discountPercentage: 14,
    stockQuantity: 60,
    brand: { id: 6, name: 'Purina', slug: 'purina' },
    categories: [{ id: 'dog', name: 'Dog', slug: 'dog' }],
    images: [
      'https://images.unsplash.com/photo-1589924691995-400dc9ecc119?w=800',
    ],
    tags: ['best-seller'],
    attributes: { 'pet-type': ['Dog'], size: ['18 lb'] },
    avgRating: 4.6,
    numReviews: 890,
    numSales: 670,
  },
  {
    id: 'PROD007',
    name: 'Interactive Cat Laser Toy',
    slug: 'interactive-cat-laser-toy',
    description: 'Automatic laser toy to keep indoor cats active.',
    price: 24.99,
    listPrice: 34.99,
    discountPercentage: 28,
    stockQuantity: 80,
    brand: { id: 7, name: 'Store Brand', slug: 'generic' },
    categories: [{ id: 'cat', name: 'Cat', slug: 'cat' }],
    images: [
      'https://images.unsplash.com/photo-1574158622682-e40e69881006?w=800',
    ],
    tags: ['new-arrival', 'featured'],
    attributes: { 'pet-type': ['Cat'], color: ['White'] },
    avgRating: 4.3,
    numReviews: 320,
    numSales: 410,
  },
  {
    id: 'PROD008',
    name: 'Ergonomic Desk Chair',
    slug: 'ergonomic-desk-chair',
    description: 'Adjustable lumbar support chair for home office.',
    price: 189,
    listPrice: 249,
    discountPercentage: 24,
    stockQuantity: 20,
    brand: { id: 8, name: 'IKEA', slug: 'ikea' },
    categories: [{ id: 'office', name: 'Office', slug: 'office' }],
    images: [
      'https://images.unsplash.com/photo-1580480055273-228ff5388ef8?w=800',
    ],
    tags: ['todays-deal', 'featured'],
    attributes: { color: ['Gray'], material: ['Mesh'] },
    avgRating: 4.4,
    numReviews: 560,
    numSales: 300,
  },
]

export const FALLBACK_SEARCH: ProductSearchResult = {
  data: products,
  total: products.length,
  page: 0,
  size: 20,
  facets: [
    {
      key: 'category',
      label: 'Category',
      type: 'CATEGORY',
      values: [
        { value: 'shoes', label: 'Shoes', count: 2 },
        { value: 'electronics', label: 'Electronics', count: 2 },
        { value: 'skincare', label: 'Skincare', count: 1 },
        { value: 'pets', label: 'Pets', count: 2 },
      ],
    },
    {
      key: 'brand',
      label: 'Brand',
      type: 'BRAND',
      values: [
        { value: 'nike', label: 'Nike', count: 1 },
        { value: 'adidas', label: 'Adidas', count: 1 },
        { value: 'sony', label: 'Sony', count: 1 },
      ],
    },
    {
      key: 'color',
      label: 'Color',
      type: 'ATTRIBUTE',
      values: [
        { value: 'Black', label: 'Black', count: 3 },
        { value: 'White', label: 'White', count: 2 },
      ],
    },
  ],
}
